### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by stefeis** [sarabanjina/mycomfort#2]
hi!
I got my windhager biowin 3 weeks ago and I was very happy to find an integration for HA but it doesn´t work for me and my knowledge in python = "0".
so I hope you can support me...

I´m running 2022.2.9, local connection is ok (also tested by browser).
all mycomfort entities are visible but not available.

that´s what I find at the log:
Logger: homeassistant.helpers.entity
Source: custom_components/mycomfort/mycomfortclient/myComfortGateway.py:163
Integration: myComfort Windhager integration (documentation, issues)
First occurred: 8. April 2022, 20:31:42 (10716 occurrences)
Last logged: 11:23:41

Update for sensor.mycomfort_biowin_2_pellet_consumption_since_bulk_fill fails
Update for sensor.mycomfort_biowin_2_pellet_consumption_total fails
Update for sensor.mycomfort_biowin_2_boiler_operating_time_cleaning fails
Update for sensor.mycomfort_biowin_2_boiler_operating_time_main_cleaning fails
Update for sensor.mycomfort_biowin_2_boiler_operating_time_maintenance fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mycomfort/sensor.py", line 273, in update
    self._state = self._sensor[CONF_GETTER](self._api)
  File "/config/custom_components/mycomfort/sensor.py", line 77, in <lambda>
    CONF_GETTER: lambda api: api.getBoilerTemperature(),
  File "/config/custom_components/mycomfort/mycomfortclient/myComfortBoiler.py", line 30, in getBoilerTemperature
    return self._gateway.value("/1/" + self._id + "/0/" + self._gateway.oid("Boiler temp. actual value") + "/0")
  File "/config/custom_components/mycomfort/mycomfortclient/myComfortGateway.py", line 163, in oid
    id,subid = self._VarIdentTexte.getid(description)
TypeError: cannot unpack non-iterable NoneType object

thanks!
stefan

**Comment by sarabanjina** [comment]
Hi,

According to the error in logs you sent, my integration isn't able to find the string "Boiler temp. actual value" in the "VarIdentTexte_xx" on your gateway. Can you post the content of this file on your gateway :
http://x.x.x.x/res/xml/VarIdentTexte_en.xml

Cheers,
Nicolas

**Comment by sarabanjina** [comment]
I just post a patch to mycomfortclient to prevent your crash. Can you try it and post your VarIdentTexte_en.xml?

Cheers,
Nicolas

**Comment by stefeis** [comment]
hi Nicolas.

thanks a lot for your support - that´s just great!
sorry, I didn´t manage to run it after having updated the 2 files and reboot.

2022-05-01 18:34:06 ERROR (SyncWorker_4) [mycomfortclient] Exception getting VarIdentTexte from server
2022-05-01 18:34:06 ERROR (SyncWorker_4) [mycomfortclient] Exception getting AufzaehlTexte from server

Logger: mycomfortclient
Source: custom_components/mycomfort/mycomfortclient/VarIdentTexte.py:38
Integration: myComfort Windhager integration ([documentation](https://github.com/sarabanjina/mycomfort), [issues](https://github.com/sarabanjina/mycomfort/issues))
First occurred: 18:34:06 (1 occurrences)
Last logged: 18:34:06
Exception getting VarIdentTexte from server

Logger: mycomfortclient
Source: custom_components/mycomfort/mycomfortclient/AufzaehlTexte.py:36
Integration: myComfort Windhager integration ([documentation](https://github.com/sarabanjina/mycomfort), [issues](https://github.com/sarabanjina/mycomfort/issues))
First occurred: 18:34:06 (1 occurrences)
Last logged: 18:34:06

Exception getting AufzaehlTexte from server

when I open the url you sent me I just get "Welcome to your Windhager InfowinTouch hosting nginx! You can now access the comWinStack API." how can I access this file or get the content?

thanks
stefan

**Comment by stefeis** [comment]
hi.
now it looks like this:
Unable to decode data from myComfort gateway
19:34:20 – (FEHLER) myComfort Windhager integration (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal um 19:32:20 aufgetreten und erscheint 6 mal
Exception getting AufzaehlTexte from server
19:31:15 – (FEHLER) myComfort Windhager integration (benutzerdefinierte Integration)
Exception getting VarIdentTexte from server
19:31:15 – (FEHLER) myComfort Windhager integration (benutzerdefinierte Integration)

**Comment by sarabanjina** [comment]
Hi,

It seems that you don't have the same gateway as mine. Can you post  a screenshot to see the web interface?

![windhager](https://user-images.githubusercontent.com/9408486/167696293-8c5ccf12-97e8-4a7e-88b9-2ca5a0e1d482.png)

Cheers,
Nicolas

**Comment by sarabanjina** [comment]
Hi,

I think I know why it isn't working : There is now a whole new (external) controller called Infinity TA. I found this info here : [Windhager BioWin (MES Infinity Steuerung) in den HS einbinden](https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1280862-windhager-biowin-mes-infinity-steuerung-in-den-hs-einbinden)

However, it seems that you can query the datapoints in the same manner... You could try my client in debug mode to see what you get : 
`python3 -m mycomfortclient --hostname x.x.x.x --username USER --password 'xxxxxxxx' --debug`

Cheers,
Nicolas

**Comment by stefeis** [comment]
Hi Nicolas.

 

That´s true, it´s an external controller conncted to biowin 2 touch, I don´t know what got used before.

I honestly don’t have any experience with python, but it seems to be time for it 😊

Thanks a lot for your support!

 

Regards

stefan

 

Von: sarabanjina ***@***.***> 
Gesendet: Dienstag, 10. Mai 2022 21:05
An: sarabanjina/mycomfort ***@***.***>
Cc: stefeis ***@***.***>; Author ***@***.***>
Betreff: Re: [sarabanjina/mycomfort] TypeError: cannot unpack non-iterable NoneType object (Issue #2)

 

Hi,

I think I know why it isn't working : There is now a whole new (external) controller called Infinity TA. I found this info here : Windhager BioWin (MES Infinity Steuerung) in den HS einbinden <https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1280862-windhager-biowin-mes-infinity-steuerung-in-den-hs-einbinden> 

However, it seems that you can query the datapoints in the same manner... You could try my client in debug mode to see what you get :
python3 -m mycomfortclient --hostname x.x.x.x --username USER --password 'xxxxxxxx' --debug

Cheers,
Nicolas

**Comment by sarabanjina** [comment]
Hi,

If you would like to, I can have a look to your gateway to estimate the work needed and the differences with the old gateway...

Regards,
Nicolas

**Comment by stefeis** [comment]
Wow, thanks!

I´ll try first to use the pyhton3 script and tell you what happened, and if needed I´m happy to show you the new gateway.

Actually I´m a bit in stress, so I don´t know when I´ve time for it. I already shut down the biowin, but for testing I´ll turn it on again.

 

Regards

stefan

 

Von: sarabanjina ***@***.***> 
Gesendet: Mittwoch, 11. Mai 2022 09:49
An: sarabanjina/mycomfort ***@***.***>
Cc: stefeis ***@***.***>; Author ***@***.***>
Betreff: Re: [sarabanjina/mycomfort] TypeError: cannot unpack non-iterable NoneType object (Issue #2)

 

Hi,

If you would like to, I can have a look to your gateway to estimate the work needed and the differences with the old gateway...

Regards,
Nicolas

**Comment by sarabanjina** [comment]
Hi,

You could try these urls first to see if the api is the same: 
http://x.x.x.x/api/1.0/datapoints (cached values on gateway)
http://x.x.x.x/api/1.0/datapoint/1/60/0/0/7/0 (actual boiler temperature)

Regards,
Nicolas

**Comment by stefeis** [comment]
Hi Nicolas.

Sorry, for coming back to you so late, but I turned on biowin on again for 2 weeks.

 

I tried your links:

 



 



 

The value of 26,5 is correct! Time stamp is not ok, I´ve to check why this I wrong.

Can I try other OID-combinations?

 

I just copied newest files onto HA, restarted and go these log entries:



 



 



 



 

Biowintouch got an update yesterday and the technician told me that the mobile app will get active functions in appr. 1 month!? I guess the controller will also get an update for this.

 

Best regards

stefan

 

 

Von: sarabanjina ***@***.***> 
Gesendet: Mittwoch, 11. Mai 2022 11:38
An: sarabanjina/mycomfort ***@***.***>
Cc: stefeis ***@***.***>; Author ***@***.***>
Betreff: Re: [sarabanjina/mycomfort] TypeError: cannot unpack non-iterable NoneType object (Issue #2)

 

Hi,

You could try these urls first to see if the api is the same:
http://x.x.x.x/api/1.0/datapoints (cached values on gateway)
http://x.x.x.x/api/1.0/datapoint/1/60/0/0/7/0 (actual boiler temperature)

Regards,
Nicolas

**Comment by domfie** [comment]
Hi Nicolas, hi Stefan,

I think this could be the InfoWin Touch Server. It's a control display with a network interface. It is connected to the LON Bus of the Heater and can identify all used components and read/set all values. The API functionality is the same as for the RC7030 but  I also have values in this online interface where I do not see any labels for. 

I have written a simple python script which just pushes the values I am interested in to openhab REST API. But since last week my pi crashed and the backup of openhab was not really working out of the box (and I personally dislike Java), I am going to move over to HomeAssistant. 

@sarabanjina thank you for the HA addon, I will have a look how to make it work with the InfoWin Touch.
@stefeis does your control panel look like this?
![winhager](https://user-images.githubusercontent.com/6722370/205488397-0ee4e170-9e10-47ea-8cb6-26f844370b88.PNG)

The webinterface looks also identically:
![InfoWin](https://user-images.githubusercontent.com/6722370/205488508-efb97600-5eca-4dd6-8ad9-2101bc8c33f4.PNG)

I see 3 different modules in the controller:
- BioWIN XL: The heater
- UMUMLZ: The controller for the radiator circuit (being able to control two heating circuits, but I only have one)
- WFBPK: The controller for the buffer circuit

I had contacted windhager to get to know what the cryptic designation should mean and got following explanation in german:

> Funktionsmodule
> 
> UMUMLZ
> 
> U - Umwälzpumpe Heizkreis 1
> M - Mischer Heizkreis 1
> U - Umwälzpumpe Heizkreis 2
> M - Mischer Heizkreis 2
> L - Ladepumpe Warmwasser
> Z - Zirkulationspumpe
> 
> Beim WFBPK ist es so das dieses Modul 2 Funktionen hat 
> - Pufferladung von einem automatischen Wärmeerzeuger (zb. Pelletskessel)
> - Pufferladung von einem händisch beschickten Wärmerzeuger (Holzkessel)
> - Ansteuerung eines fremden (nicht Windhager) automatschen Wärmeerzeugers
> 
> Da diese Seite die Sie nutzen nicht für Anlagenbetreiber freigegen ist gibt es hier keine Übersetzung der Variablen.

Here is the complete script. It accesses all Items through 
http://192.168.1.103/api/1.0/lookup/.

If we look at the ID for the total pellet consumption ( 1/60/0/23/103/0) it's this structure:
1 - NetId
60 - DeviceId (BioWIN XL)
0 - Function of the module (Heater)
23 - Subfunction 
103 - Key
0 - Version (0 seams to be the real time value)

`import logging
import requests
from requests.auth import HTTPDigestAuth

CONFIG = {
"wOutside_temperature": "1/15/0/0/0/0",
"wPellet_consumption": "1/60/0/23/103/0",

"wHeater_state": "1/15/0/3/50/0",
"wHeater_preTemp": "1/15/0/0/2/0",
"wHeater_burnTemp": "1/60/0/0/7/0",
"wHeater_pump": "1/15/0/1/20/0",
"wHeater_mixer": "1/15/0/1/21/0",

"wBuffer_state": "1/16/1/20/15/0",
"wBuffer_PostTemp": "1/16/1/0/8/0",
"wBuffer_top": "1/16/1/21/65/0",
"wBuffer_bottom": "1/16/1/21/66/0",
"wBuffer_pump": "1/16/1/1/22/0",
"wBuffer_mixer": "1/16/1/1/102/0",

"wBurner_alarm": "1/60/0/2/0/0",
"wBurner_runtime": "1/60/0/2/81/0",
"wBurner_cleantime": "1/60/0/20/61/0",
"wBurner_performance": "1/60/0/0/9/0",
"wBurner_startcount": "1/60/0/2/80/0",
"wBurner_exhaustTemp": "1/60/0/0/11/0",
"wBurner_innerTemp": "1/60/0/0/7/0",
"wBurner_phase": "1/60/0/2/1/0"
}

POST_URL = "http://192.168.1.106:8080/rest/items/"
GET_URL = "http://192.168.1.103/api/1.0/lookup/"

for key in CONFIG:
    try:
        r = requests.get(GET_URL + CONFIG[key], auth=HTTPDigestAuth('Service', '123'))
        data = r.json()['value']
        r = requests.post(url=POST_URL + key, data=data)
    except BaseException as e:
        print(str(e))
`

I will try to upload a tcpdump of the interaction with the interface.

**Comment by stefeis** [comment]
no totally different:
![image](https://github.com/sarabanjina/mycomfort/assets/79421488/cef70ba4-5c48-44b7-8afc-af94da0b3808)
![image](https://github.com/sarabanjina/mycomfort/assets/79421488/62134dd5-c950-491b-929a-c82bce1028e6)

![image](https://github.com/sarabanjina/mycomfort/assets/79421488/e04baa4a-f47d-48a8-a8bc-1deb7fc47f4a)

**Comment by domfie** [comment]
@stefeis congratulations, I just got the same control for my second windhager heater. Looks like they are now using off the shelf CAN-Bus Controllers with custom firmware to control the peripherals. The device which shows "Passwort eingeben" is actually this controller https://www.ta.co.at/x2-frei-programmierbare-regler/uvr610s-mit-modbus-schnittstelle. It runs a program flashed by windhager and thus has a password on it which is unkown. Everything can be set up using the CAN Monitor.

The server which serves the nginx message is inside of your biowin heater. It can be accessed just like the older units, but is lacking the Web-UI. Furthermore this unit is only in charge of controlling of the heater and the buffer storage.  Thus you can access all values associated to them, but no parameters like the Vorlauftemperatur. But for me it's sufficient to see the current pellet consumption and the temperatures of the buffer. I will try to add this functionality over christmas (hopefully got time :laughing: )

Since I fear loosing local access to the api when using the Windhager App, I can not test out if my assumption that I can not see the parameters of the peripherals is correct

**Comment by stefeis** [comment]
thanks for your investigations :-) I also use the windhager app. right now windhager is trying to optimize my heater because it started up to 26 times a day... now we are at 19, hope it will get lower. I´m looking forward to you changes - if you find some time. don´t hurry, enjoy some silent days at home :-)

**Comment by domfie** [comment]
@stefeis are you able to see values beyond the ones of the heater in the app? Like the outside temperature or the Vorlauftemperatur? Just had a look though all advertised functions and I can only see the heater and buffer values though the API. If you see more it could be valueable to checkout their app api?

**Comment by stefeis** [comment]
using the mobile app I see at "biowin": Reinigung (h), Hauptreinigung (h), Wartung (h), aktuelle Leistung (%), Kesseltemperatur, Kesseltemperatur Sollwert, Brennkammertemperatur, Abgastemperatur, Anzahl Brennerstarts, Brennstoffverbrauch gesamt (t), Befüllgrad Vorratsbehälter (%), Befüllgrad Lagerraum (%), Betriebsstunden (h),
at "Heizkreis UMLZ(1): Raumtemperatur aktueller Wert, Raum Temperatur Sollwert, WW Temperatur aktuell, WW Temperatur Soll, Aussentemperatur, Vorlauf Temperatur aktuell, Vorlauftemperatur Soll, Betriebsart
at "Heizkreis UM (2)": Raumtemperatur SOll, AUssentemperatur, VOrlauf Temperatur aktuell, Vorlauf Temperatur soll, Betriebsart,
hope this helps...

**Comment by hartmannf** [comment]
Hi 


>  I have written a simple python script which just pushes the values I am interested in to openhab REST API. But since last week my pi crashed and the backup of openhab was not really working out of the box (and I personally dislike Java), I am going to move over to HomeAssistant.

I do at the moment the same moving to HA and once works perhaps give a try to OHab

>  @sarabanjina thank you for the HA addon, I will have a look how to make it work with the InfoWin Touch. @stefeis does your control panel look like this? ![winhager](https://user-images.githubusercontent.com/6722370/205488397-0ee4e170-9e10-47ea-8cb6-26f844370b88.PNG)

for info: Since a few days, after Firmware upgrade from technician: I know that this is v3 or earlier. v4 has never been released, and now v5 looks like the windhager app: 
![IMG_2150](https://github.com/user-attachments/assets/c370bde3-a367-4481-85fa-ca825f51a65f)

> The webinterface looks also identically: ![InfoWin](https://user-images.githubusercontent.com/6722370/205488508-efb97600-5eca-4dd6-8ad9-2101bc8c33f4.PNG)

Up to now I have not been able to get the Webinterface working. USER and Password are for sure setup properly. 

-> <http://<IP-Adress>/rest/items/>


> Welcome to your Windhager InfowinTouch hosting nginx!
>
>You can now access the comWinStack API.

-> <http://<IP_Adress>/api/1.0/lookup/>

Response: 

> Here is the complete script. It accesses all Items through http://192.168.1.103/api/1.0/lookup/.
> POST_URL = "http://192.168.1.106:8080/rest/items/" GET_URL = "http://192.168.1.103/api/1.0/lookup/"
> for key in CONFIG: try: r = requests.get(GET_URL + CONFIG[key], auth=HTTPDigestAuth('Service', '123')) data = r.json()
>['value'] r = requests.post(url=POST_URL + key, data=data) except BaseException as e: print(str(e)) `


On New version up to know I have not been able to get: 
-> <http://<IP_Adress>/api/1.0/lookup/>
Response: 
`[
    1
]`
->  <http://<IP_Adress>/api/1.0/lookup/1/>
response: 
`[
    {
        "device": 
        {
            "id": 7
        },
        "name": "InfoWinTouch",
        "neuronId": "234300E5FD",
        "nodeId": 90,
        "programId": "90010022020a0501",
        "subnet": 1,
        "group": "",
        "FE01msg": "MB 00I OK",
        "functions": 
        [
            {
                "fctId": 32,
                "fctType": -1,
                "lock": false,
                "name": "NV's"
            }
        ]
    },
    {
        "device": 
        {
            "id": 2
        },
        "name": "InfinityPlusWall",
        "neuronId": "002343001d7e",
        "nodeId": 15,
        "programId": "90010021020a0501",
        "subnet": 1,
        "group": "3",
        "FE01msg": "FMP 09I OK",
        "functions": 
        [
            {
                "fctId": 0,
                "fctType": 1,
                "lock": false,
                "name": "HK1 Radiatoren"
            },
            {
                "fctId": 1,
                "fctType": 1,
                "lock": false,
                "name": "HK2 Bodenheizung"
            },
            {
                "fctId": 2,
                "fctType": 5,
                "lock": true,
                "name": "Solar"
            },
            {
                "fctId": 3,
                "fctType": 2,
                "lock": false,
                "name": "Warmwasser"
            }
        ]
    },
    {
        "device": 
        {
            "id": 2
        },
        "name": "BioWIN2",
        "neuronId": "0024bd0484f9",
        "nodeId": 60,
        "programId": "90010014150a0501",
        "subnet": 1,
        "group": "3",
        "FE01msg": "FMP 09I OK",
        "functions": 
        [
            {
                "fctId": 0,
                "fctType": 9,
                "lock": false,
                "name": "BioWIN"
            },
            {
                "fctId": 1,
                "fctType": -1,
                "lock": true,
                "name": "-"
            },
            {
                "fctId": 2,
                "fctType": -1,
                "lock": true,
                "name": "-"
            },
            {
                "fctId": 3,
                "fctType": -1,
                "lock": true,
                "name": "-"
            },
            {
                "fctId": 4,
                "fctType": -1,
                "lock": true,
                "name": "-"
            },
            {
                "fctId": 5,
                "fctType": -1,
                "lock": true,
                "name": "-"
            },
            {
                "fctId": 6,
                "fctType": -1,
                "lock": true,
                "name": "-"
            },
            {
                "fctId": 7,
                "fctType": -1,
                "lock": true,
                "name": "-"
            },
            {
                "fctId": 8,
                "fctType": -1,
                "lock": true,
                "name": "-"
            },
            {
                "fctId": 9,
                "fctType": 21,
                "lock": true,
                "name": "-"
            }
        ]
    }
]`

[(http://192.168.1.55/res/xml/VarIdentTexte_en.xml)]
Can`t be downloaded. wrong location or not accesible I do not know. 

Is there somebody that has an idee how I could mak it work? 
thanks
F


Update 20241124 --> There exist Touch Display 1004 and there is the web interface not open. You need Touch Display 1009 to Access the Webinterface. <http://<IP-Adress>>

**Comment by stefeis** [comment]
no, looks totaly different. right now I´ve software version 3.32, but I´m sure I´ll get the new version at next visit of the technician - probably in January.
