### ISSUE TITLE
lots of errors

### ISSUE THREAD

**Issue by maxandersen** [sarabanjina/mycomfort#4]
I finally got the "Service" user and password to try out this integration for my windhager pelletburner.

It does log in and starts setting up sensors with proper names but getting data seem to fail with lots of errors.

when I login to the heater directly I just see:

"Welcome to your Windhager Infowin UI hosting nginx!

You can now access the comWinStack API."

but i know the username/password works and in logs I can see it get further with that username/password combo but I get errors like these:

```
023-10-17 18:25:30.576 INFO (MainThread) [homeassistant.setup] Setting up mycomfort
2023-10-17 18:25:30.753 INFO (SyncWorker_4) [mycomfortclient] Unknown device found : InfoWinPlus (90)
2023-10-17 18:25:30.753 INFO (SyncWorker_4) [mycomfortclient] Module found : UMUMLZ (15)
2023-10-17 18:25:30.753 INFO (SyncWorker_4) [mycomfortclient] Boiler found : BioWIN 2 (60)
2023-10-17 18:25:30.871 ERROR (SyncWorker_4) [mycomfortclient] Exception getting VarIdentTexte from server
2023-10-17 18:25:30.963 ERROR (SyncWorker_4) [mycomfortclient] Exception getting AufzaehlTexte from server
2023-10-17 18:25:31.004 ERROR (SyncWorker_4) [mycomfortclient] Exception getting ErrorTexte from server : mismatched tag: line 19, column 2
2023-10-17 18:25:31.107 INFO (MainThread) [homeassistant.setup] Setup of domain mycomfort took 0.5 seconds
2023-10-17 18:25:33.792 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mycomfort
2023-10-17 18:25:33.897 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mycomfort platform for sensor
File "/config/custom_components/mycomfort/sensor.py", line 220, in setup_platform
File "/config/custom_components/mycomfort/mycomfortclient/myComfortModule.py", line 40, in isDHWCircuit
2023-10-17 18:25:33.907 INFO (MainThread) [homeassistant.components.water_heater] Setting up water_heater.mycomfort
2023-10-17 18:25:33.907 INFO (MainThread) [homeassistant.components.climate] Setting up climate.mycomfort
2023-10-17 18:25:34.362 ERROR (MainThread) [homeassistant.components.water_heater] Error while setting up mycomfort platform for water_heater
File "/config/custom_components/mycomfort/water_heater.py", line 65, in setup_platform
File "/config/custom_components/mycomfort/mycomfortclient/myComfortModule.py", line 40, in isDHWCircuit
2023-10-17 18:26:34.275 ERROR (SyncWorker_42) [custom_components.mycomfort.climate] Unable to decode data from myComfort server
2023-10-17 18:26:34.766 ERROR (SyncWorker_34) [mycomfort] Unable to decode data from myComfort gateway
2023-10-17 18:26:34.860 ERROR (SyncWorker_27) [mycomfort] Unable to decode data from myComfort gateway
```

```
Error while setting up mycomfort platform for water_heater
6:25:34 PM – (ERROR) Water Heater (custom integration)
Error while setting up mycomfort platform for sensor
6:25:33 PM – (ERROR) Sensor (custom integration)
Exception getting ErrorTexte from server : mismatched tag: line 19, column 2
6:25:31 PM – (ERROR) myComfort Windhager integration (custom integration)
Exception getting AufzaehlTexte from server
6:25:30 PM – (ERROR) myComfort Windhager integration (custom integration)
Exception getting VarIdentTexte from server
6:25:30 PM – (ERROR) myComfort Windhager integration (custom integration)
```

**Comment by maxandersen** [comment]
here is output of mycomforclient:

```
Retrieving url http://192.168.0.223:80/api/1.0/lookup
Retrieving url http://192.168.0.223:80/api/1.0/lookup/1
Unknown device found : InfoWinPlus (90)
Module found : UMUMLZ (15)
Boiler found : BioWIN 2 (60)
Refreshing cache...
Retrieving url http://192.168.0.223:80/api/1.0/datapoints
Retrieving url http://192.168.0.223:80/res/xml/VarIdentTexte_en.xml
Exception getting VarIdentTexte from server
Retrieving url http://192.168.0.223:80/res/xml/AufzaehlTexte_en.xml
Exception getting AufzaehlTexte from server
Retrieving url http://192.168.0.223:80/res/xml/ErrorTexte_en.xml
Exception getting ErrorTexte from server : mismatched tag: line 19, column 2
Gateway(hostname=192.168.0.223) (name=) (serial_no=) (cache_duration=60) instantiated.
Boiler serial_no : 042b17c33600
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler Alarm : Unknown error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler actual temperature : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler setpoint temperature : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler exhaust temperature : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler operating hours : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler current output : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler current mode : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler cleaning stage 1 : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler cleaning stage 2 : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler full service : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler burner starts : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler pellet consumption since bulk fill : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/60/0/error/0
Boiler pellet consumption total : error
Module serial_no : 0702a5952101
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/15/0/error/0
Outside temperature : error
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/15/0/0/2/0
Actual flow temperature : 60.3
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/15/0/1/2/0
Setpoint flow temperature : 49.6
Retrieving url http://192.168.0.223:80/api/1.0/datapoint/1/15/0/error/0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/manderse/code/winhager/mycomfortclient/__main__.py", line 63, in <module>
    main()
  File "/Users/manderse/code/winhager/mycomfortclient/__main__.py", line 53, in main
    if module.isDHWCircuit():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manderse/code/winhager/mycomfortclient/myComfortModule.py", line 40, in isDHWCircuit
    return int(self._gateway.value("/1/" + self._id + "/0/" + self._gateway.oid("DHW circuit") + "/0", self._gateway._cacheDuration * 60))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'error'
```

**Comment by maxandersen** [comment]
I tried printing the xml strings and I get this:

```
<!DOCTYPE html>
<html>
<head>
<title>InfowinTouch MB6622</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to your Windhager Infowin UI hosting nginx!</h1>
<p></p>
<br>

<p><em>You can now access the comWinStack API.</em></p>
</body>
</html>
```

so looks like the API is not as expected ;/

**Comment by sarabanjina** [comment]
Hello,

It seems that XML mapping files are not downloaded from your Infowin interface. Without them, I can't translate OID to human strings.

Can you try to download them directly in a browser (and try different languages) : 
http://192.168.0.223:80/res/xml/VarIdentTexte_de.xml
http://192.168.0.223:80/res/xml/VarIdentTexte_en.xml

I found another project working with Infowin Touch and the URL are the same : 
https://github.com/sessl3r/windhager

Cheers.

**Comment by hartmannf** [comment]
> Hello,
> 
> It seems that XML mapping files are not downloaded from your Infowin interface. Without them, I can't translate OID to human strings.
> 
> Can you try to download them directly in a browser (and try different languages) : http://192.168.0.223:80/res/xml/VarIdentTexte_de.xml http://192.168.0.223:80/res/xml/VarIdentTexte_en.xml
> 
> I found another project working with Infowin Touch and the URL are the same : https://github.com/sessl3r/windhager
> 
> Cheers.

Hi 

I confirm I do also have a InfowinTouch MB6622 and got similar behave. on my confort. I think a few things have changed or are not accessible by winhager. I don`t think that it is because app is accesing at same time to Biowin but of course not sure. 
 
My interface has been updated last week to newest Firmware and looks like the app. 

![IMG_2150](https://github.com/user-attachments/assets/3e62311e-720c-4372-ad2d-3439fb6e401d)

I can access several OID over the browser according to Excel List 
[https://forum.iobroker.net/assets/uploads/files/1626989692913-2021-07-22-windhager-webserver-und-oid.xlsx](url)

Might there be somebody to got an idea on what is the problem? 

thanks
f
